simplePipe: simplePipe.c
	gcc -Wall -ansi -pedantic simplePipe.c -o p

dup: dup.c
	gcc -Wall -ansi -pedantic dup.c -o p

dictionary: dictionary.c
	gcc -Wall -ansi -pedantic dictionary.c -o p -std=gnu99

test: test.c
	gcc -Wall -ansi -pedantic test.c -o p

passing: passing.c
	gcc -Wall -ansi -pedantic passing.c -o p -std=gnu99