listener:
	gcc -Wall -pedantic -ansi listener.c -o listener.exe -std=gnu99
talker:
	gcc -Wall -pedantic -ansi talker.c -o talker.exe -std=gnu99
broadcastTalker:
	gcc -Wall -pedantic -ansi broadcastTalker.c -o broadcastTalker.exe -std=gnu99
chat:
	gcc -Wall -pedantic -ansi chat.c -o chat.exe -std=gnu99
calendar:
	gcc -Wall -pedantic -ansi calendar.c -o calendar.exe -std=gnu99

clean:
	rm *.exe