listener:
	gcc -Wall -pedantic -ansi listener.c -o listener.exe -std=gnu99
talker:
	gcc -Wall -pedantic -ansi talker.c -o talker.exe -std=gnu99
chat:
	gcc -Wall -pedantic -ansi chat.c -o chat.exe -std=gnu99

clean:
	rm *.exe