monkeys: cw3/monkeys.c
	gcc -Wall -ansi -pedantic cw3/monkeys.c -o monkeys.exe -std=gnu99 -pthread

monkeysNew: cw3/monkeysNew.c
	gcc -Wall -ansi -pedantic cw3/monkeysNew.c -o monkeysNew.exe -std=gnu99 -pthread

test: test.c
	gcc -Wall -ansi -pedantic test.c -o test.exe -std=gnu99

test2: test2.c
	gcc -Wall -ansi -pedantic test2.c -o test2.exe -std=gnu99 -pthread

clean:
	rm *.exe