morse: morse.c
	gcc -Wall -ansi -pedantic morse.c -o morse.exe -std=gnu99

sessions: sessions.c
	gcc -Wall -ansi -pedantic sessions.c -o sessions.exe -std=gnu99

lotto: lotto.c
	gcc -Wall -ansi -pedantic lotto.c -o lotto.exe -std=gnu99

matrix: matrix.c
	gcc -Wall -ansi -pedantic matrix.c -o matrix.exe -std=gnu99 -lncurses

clean:
	rm *.exe