simple:
	gcc -Wall -pedantic -ansi simplee/server.c -o server.exe -std=gnu99;
	gcc -Wall -pedantic -ansi simplee/client.c -o client.exe -std=gnu99

chat:
	gcc -Wall -pedantic -ansi chatt/client.c -o client.exe -std=gnu99;
	gcc -Wall -pedantic -ansi chatt/server.c -o server.exe -std=gnu99

browser:
	gcc -Wall -pedantic -ansi browser.c -o browser.exe -std=gnu99;

clean:
	rm *.exe