hello: hello.c
	gcc -Wall -ansi -pedantic hello.c -o p -std=gnu99 -pthread

func: func.c
	gcc -Wall -ansi -pedantic func.c -o p -std=gnu99 -pthread

cond: cond.c
	gcc -Wall -ansi -pedantic cond.c -o p -std=gnu99 -pthread

extra: extra.c
	gcc -Wall -ansi -pedantic extra.c -o p -std=gnu99 -pthread

randomsearch: randomsearch.c
	gcc -Wall -ansi -pedantic randomsearch.c -o p -std=gnu99 -pthread